### ISSUE TITLE
Spring animations don't work until one complete cycle of cards

### ISSUE THREAD

**Issue by Bradmartin0905** [driftyco/ionic-ion-tinder-cards#18]
I've tried numerous approaches to resolve this, logged every event possible to find the reason but no luck.

I've copied and pasted the working example even and I have the same result. Array size doesn't matter. The first cycle of cards they can simply be dragged around the screen and on release they transition back to the deck (they're being spliced however because it's a full left/right drag from demo code). After the first swipe of the entire stack, the animations start firing correctly and the 'spring' works Partial swipes animate correctly. It just works well after the first cycle of cards.

**Comment by mlynch** [comment]
Going to close since I can't reproduce. I just added `preventDefault` to see if that works. Let me know and I'll reopen if not.

**Comment by leandroz** [comment]
Hey guys!
I still have the problem with the side menu, i have it in the left and is opened in the left swipe.
I only allow the side menu to toggle with a button, i have drag-content="false" but still not working ok.
Something that maybe is helpful, the first time the view with the cards is showed, the side menu is abled to be dragged, but if i go to another options of the side menu and then return to the view with the cards is working ok and the side menu doesn't drag.

**Comment by keithdmoore** [comment]
If you are using beta 13, you can do this in your app.js run block:

````
.run(function($rootScope, $ionicPlatform, $ionicSideMenuDelegate, ENV) {
  $rootScope.$on('$stateChangeSuccess', function () {
    // By default, we want to allow the side-menu to be dragged. Some views may need to disable it
    // so we want to enable it after a successful state change
    $ionicSideMenuDelegate.canDragContent(true);
  });
````

Then in your controller for your view that has the "cards" you can do this:

````
  // Disable side-menu drag so that it doesnt interfere with our swipe cards functionality
  $ionicSideMenuDelegate.canDragContent(false);
````

**Comment by leandroz** [comment]
Thanks for your response!
I am using Beta 14, i have already done that but still the same problem.

**Comment by keithdmoore** [comment]
I see.  I have not tried to migrate to beta 14 as of yet.  There are many breaking changes.  Some of them have to do with the side menu.
