### ISSUE TITLE
Use unshift to add new cards to the bottom of the stack

### ISSUE THREAD

**Issue by huttj** [driftyco/ionic-ion-tinder-cards#20]
The current example uses Array.shift to add new cards, which results in the card being placed on the top of the stack.

It should use Array.unshift, instead:

    $scope.addCard = function() {
        var newCard = cardTypes[Math.floor(Math.random() * cardTypes.length)];
        newCard.id = Math.random();
        $scope.cards.unshift(angular.extend({}, newCard));
    }

[Example](http://codepen.io/anon/pen/loIHC)

**Comment by mlynch** [comment]
Merged #27, thanks.
