### ISSUE TITLE
Causing error after the first card is swiped out

### ISSUE THREAD

**Issue by scvdance** [driftyco/ionic-ion-tinder-cards#29]
Hi,

I am having issues with this library. After swiping the first card out, it keeps printing error on the console:

Uncaught TypeError: Cannot read property 'style' of undefined

The error happens here:  ionic.tdcards.js:371

position = card.style.transform || card.style.webkitTransform;

Could you please take a look at this?

**Comment by mlynch** [comment]
Fixed, thanks! Also the logic was wrong so it wasn't brining the cards up correctly anyways.
