### ISSUE TITLE
isolate scope issue after upgrade

### ISSUE THREAD

**Issue by toddrimes** [driftyco/ionic-ion-tinder-cards#38]
I just upgraded my project to Angular 1.3.8 and ionic beta 14.  Almost everything is working except for &lt;td-card&gt; inside &lt;td-cards&gt;.  Now my cards do not render at all and I get: https://docs.angularjs.org/error/$compile/multidir and I know it has something to do with the tdCard and tdCards directives both requesting isolate scopes (though it *used* to work?).

If I remove the following 
```
         scope: {
            onSwipeLeft: '&',
            onSwipeRight: '&',
            onTransitionLeft: '&',
            onTransitionRight: '&',
            onTransitionOut: '&',
            onPartialSwipe: '&',
            onSnapBack: '&',
            onDestroy: '&'
          },
```
...from the tdCard (child?) directive, the cards render and even still 'swipe' but the behaviors (now undefined) of course don't work.

Any pointers?

**Comment by mlynch** [comment]
Looking into it right now, will fix here. Thanks

**Comment by mlynch** [comment]
Fixed, thanks!

**Comment by toddrimes** [comment]
Awesome - thank you!



	 	
Todd Rimes
about.me/toddrimes
 <http://about.me/toddrimes?promo=email_sig>

**Comment by keithdmoore** [comment]
@mlynch 
The error goes away but the cards are very unstable.   My workaround was to remove the ng-controller and take the CardCtrl contents and place them in my view controller.   The only issue I have found with that is the ability to obtain the swipe card using the TDCardDelegate.
