### ISSUE TITLE
card.swipe() not working

### ISSUE THREAD

**Issue by dyllen** [driftyco/ionic-ion-tinder-cards#39]
As far as I can tell the following should cause the current swipeable card to be swiped off screen, however I can't seem to get it to work. Has anyone had any success with being able to trigger a swipe with this method?

    var card = $ionicSwipeCardDelegate.getSwipebleCard($scope);
    card.swipe();

**Comment by keithdmoore** [comment]
See this PR: 
https://github.com/driftyco/ionic-ion-tinder-cards/pull/14

**Comment by mlynch** [comment]
Closing with #14 getting merged.
