### ISSUE TITLE
Missing controller for directive 'tdCard'

### ISSUE THREAD

**Issue by joejuzl** [driftyco/ionic-ion-tinder-cards#48]
Hello,

When I try and use your code (copying it almost directly from the demo into my code) I get an error:
<code> Error: [$compile:ctreq] Controller 'tdCards', required by directive 'tdCard', can't be found! </code>

In your tdCard directive there is a line:
     <code> require: '^tdCards' </code>
but that should be fine as the tdCards directive exists and has a controller....

Not sure what is wrong.

Thanks!

Joe

**Comment by keithdmoore** [comment]
Did you place your td-card inside a td-cards tag?

**Comment by joejuzl** [comment]
Wow, I was being really stupid!!

That fixed it, thanks Keith.

**Comment by keithdmoore** [comment]
Glad I could help.  Can you close this issue?
