### ISSUE TITLE
card not returned to its position

### ISSUE THREAD

**Issue by mo3taz-abdallh** [driftyco/ionic-ion-tinder-cards#55]
Hello EveryOne
I have faced the following issue is that in my Domino Game the card is not return to its original position, you could refer to the following image.
<img src="http://i.imgur.com/Que4zAz.png" />

Regards

**Comment by Yago** [comment]
Same issue, Collide don't work on Webview, only in proper browser like iOS Safari...

**Comment by ShiyangHuang** [comment]
check your console, did you miss collide.js? include it in index.html as

<script src="lib/collide/collide.js"></script>
