### ISSUE TITLE
Ability to limit amount of visible cards no matter size of array

### ISSUE THREAD

**Issue by marcfalk** [driftyco/ionic-ion-tinder-cards#56]
If one adds 20 cards to the array, from which cards are looped through, the result is currently 20 cards, all visible, on top of each other. Say I want to load in 50 cards at a time, that quickly becomes an unnecessary amount of screen estate for showing the stack itself.

See example: http://forum.ionicframework.com/t/tinder-cards-stacking-issue/12026

It would be nice with the option to limit the amount of visible cards no matter the size of the whole stack/array. Is this in the pipeline? :)

**Comment by m10l** [comment]
+1 - This would be great.

I'm currently doing something that might help you - I have two arrays for cards, one 'stage' array, which uses the td-cards/td-card directives, and a second 'holding' array containing multiple cards.

The stage array only ever contains one card. Once a card has been swiped from the stage array, a card from the holding array is moved over to replace it. As the stage array only contains one card, only two cards are ever visible at one time (though you could change this with CSS to get the stacked effect)

This feels slightly abusive of the tinder-cards ion, but for me this has gotten around a lot of issues, particularly when loading in new cards with data from an API.

Hope this helps!

**Comment by marcfalk** [comment]
@m10l Totally forgot to reply.  Thanks for your answer. I ended up doing something similar, even though I still have a few problems with positioning the cards. The javascript loves stacking/animating them cards :)

**Comment by ghost** [comment]
+1 thats a dope idea :)

**Comment by wbowlin** [comment]
Have you tried to use a limitTo filter with the ng-repeat?  

This is an example:
<td-card ng-repeat="card in cards | limitTo:4"
