### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'collide.animation')

### ISSUE THREAD

**Issue by Afondevi** [driftyco/ionic-ion-tinder-cards#61]
Hi,

I have a big problem in ionic tinder cards.
I can move my cards but the SnapBack don't work.
I don't manage to resolve it.

[Error] TypeError: undefined is not an object (evaluating 'collide.animation')  In  ionic.tdcards.js, line 308
	onSnapBack (ionic.tdcards.js, line 308)
	transitionOut (ionic.tdcards.js, line 117)
	_doDragEnd (ionic.tdcards.js, line 205)
	(fonction anonyme) (ionic.tdcards.js, line 171)

If one of you can help me I paie you a cafe :D
Thx a lot

French Guy with bad english.. Sorry.
Alexy

**Comment by keithdmoore** [comment]
Looks like your are missing the collide.js library in your index.html.

**Comment by Afondevi** [comment]
Yes it is :/

![capture d ecran 2015-04-07 a 15 38 44](https://cloud.githubusercontent.com/assets/11740298/7024323/4a697798-dd3c-11e4-8247-e542bfd37bc6.png)

**Comment by keithdmoore** [comment]
Show me your index.html file

**Comment by Afondevi** [comment]
Sure, 

![capture d ecran 2015-04-07 a 17 17 04](https://cloud.githubusercontent.com/assets/11740298/7026449/02cd2e8a-dd4a-11e4-80c2-8b8838963f2e.png)
![capture d ecran 2015-04-07 a 17 17 22](https://cloud.githubusercontent.com/assets/11740298/7026450/02f50220-dd4a-11e4-9b21-d159672a3792.png)

**Comment by keithdmoore** [comment]
If you used the yeoman ionic generator then you need to use `grunt serve`

**Comment by Afondevi** [comment]
I used that one :
https://github.com/mwaylabs/generator-m/blob/master/README.md

**Comment by keithdmoore** [comment]
Ok.  I am not familiar with that one.  Not sure what your problem is then.  Sorry.

**Comment by Afondevi** [comment]
Ok no problem, Thanks very much for your attention !

**Comment by Afondevi** [comment]
Up !

**Comment by Afondevi** [comment]
It's Ok ! I had 2 ionic.tdcards.js file in 2 folder and it make a conflict.
