### ISSUE TITLE
onSwipeLeft & onSwipeRight not called on slow swipes

### ISSUE THREAD

**Issue by baconmania** [driftyco/ionic-ion-tinder-cards#65]
When a full swipe to the left or right is done very slowly, `onDestroy()` is called, but `onSwipe[Left|Right]()` are not called.

**Comment by keithdmoore** [comment]
onTransistionLeft and onTransistionRight should be used when a drag should also be treated as a swipe. 

Pecked out from my iPhone

**Comment by rogerkerse** [comment]
+1

**Comment by cmcnamara87** [comment]
+1

**Comment by budda** [comment]
Explains why I never see any output in the console from the demo code then...

+1 for the bug.

**Comment by keithdmoore** [comment]
That's because a slow swipe is interpreted as a drag.  See my earlier comment if you want a slow swipe(aka drag) to be treated as a regular swipe.

**Comment by budda** [comment]
@keithdmoore I followed the transition and swipe events listed on http://devdactic.com/optimize-tinder-cards and hooked them up with functions to output console.log messages but nothing gets triggered.

I think the blog post is covering the same as what you mentioned in your earlier comment.

**Comment by keithdmoore** [comment]
Looks like that is a different issue.  Please open a new issue.
