### ISSUE TITLE
Dynamically added cards cause flickering

### ISSUE THREAD

**Issue by daphnawegner** [driftyco/ionic-ion-tinder-cards#70]
I am dynamically adding a card every time a swipe event is fired, I noticed that the first couple of cards after the first card always flicker (they also don't stack nice as mentioned in other posts). 

any idea how to resolve the flickering issue?

**Comment by wbowlin** [comment]
This is most likely caused by an issue with the z-order of the cards.  Try applying an inline style to alter the zorder from within the td-card directive:

```
      <td-card ng-repeat="card in cards"
               style="z-index:{{ cards.length - $index}}; -webkit-transform : translate3d(0, {{$index*4}}px, 0)"
               >
```
