### ISSUE TITLE
Drawer Opening as well

### ISSUE THREAD

**Issue by Matt2012** [driftyco/ionic-ion-tinder-cards#72]
When I swipe right the drawer menu opens as well. I guess this is a propagation issue. Not sure how to prevent it though as there is no event to use stopPropagation with.

**Comment by keithdmoore** [comment]
See the card.js file in Trendicity

**Comment by keithdmoore** [comment]
https://github.com/trendicity/trendicity

**Comment by Matt2012** [comment]
@keithdmoore Cheers!
