### ISSUE TITLE
Delay between the last "DRAG" and "DRAGEND" events

### ISSUE THREAD

**Issue by Pitouli** [driftyco/ionic-ion-tinder-cards#76]
I got something which looks a lot like the 300ms delay issue: there is a very noticeable latency when I release the card.
I added some logs for all the "dragstart", "drag" and "dragend" events, and there is clearly a pause between the last "drag" event and the "dragend" event.
I observe exactly the same delay here : http://ionicframework.com/demos/swipe-cards/ or here http://codepen.io/ionic/pen/nxEdH 
I mainly have tested on the iOS virtual machine, the android virtual machine, my browser (Chrome), and 2 android physical devices through Ionicview.

**Comment by Pitouli** [comment]
Another observation:
if I completely drag the card out of screen, I do not need to release the drag. The "dragend" event is immediately fired as soon as my cursor is out of the virtual machine.
Same behavior observed on the android virtual machine.

I do not have an android phone available at the moment (and even less an iPhone) so I cannot test for real.
But can you already tell me if you observe the same latency on the examples I gave previously, and if this latency then disappear on the real device?

**Comment by GabrielSt** [comment]
i've tested on my android device with ionic view and the performance was terrible, i'm searching if i did something wrong.
Someone have tested it?
